# Generated by Django 4.2.7 on 2023-11-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_result_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
