# Generated by Django 4.2.7 on 2023-11-29 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quiz_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='user',
            new_name='creator',
        ),
    ]
