# Generated by Django 4.2.7 on 2023-11-29 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_remove_question_quiz_quiz_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
    ]
