# Generated by Django 4.2.7 on 2023-12-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_quiz_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
