# Generated by Django 4.2.7 on 2023-12-04 13:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_quizcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizcomment',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
