# Generated by Django 4.2.7 on 2023-12-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_alter_quizcomment_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizcomment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
