# Generated by Django 4.2.7 on 2023-12-05 10:23

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_alter_result_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='quizcomment',
            name='content',
            field=models.TextField(max_length=2000),
        ),
    ]
