# Generated by Django 4.2.7 on 2023-12-13 10:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0033_alter_result_options_result_time_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=tinymce.models.HTMLField(max_length=1000),
        ),
    ]
