# Generated by Django 4.2.7 on 2023-12-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0036_alter_choice_question_alter_question_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='image',
            field=models.ImageField(default='media/no_image.jpg', null=True, upload_to='images'),
        ),
    ]
