# Generated by Django 4.2.7 on 2023-12-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0039_alter_quiz_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
